"""added thenew attr to thye table products

Revision ID: 2ef72aa9ccfc
Revises: b9a8d6295dbe
Create Date: 2025-10-14 11:54:24.126374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef72aa9ccfc'
down_revision: Union[str, Sequence[str], None] = 'b9a8d6295dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=False,server_default="0"))
    op.add_column('orders', sa.Column('discount_applied', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('discount_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'discount_codes', ['discount_code_id'], ['id'])
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'category')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'discount_code_id')
    op.drop_column('orders', 'discount_applied')
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###
