"""base model again

Revision ID: 8d12f386274b
Revises: 
Create Date: 2025-10-13 17:57:01.952838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d12f386274b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_discount_code_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'discount_code_id')
    op.drop_column('orders', 'discount_applied')
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('discount_applied', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('discount_code_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_discount_code_id_fkey'), 'orders', 'discount_codes', ['discount_code_id'], ['id'])
    # ### end Alembic commands ###
